insert into cozinha (id, nome) values (1, 'Tailandesa');
insert into cozinha (id, nome) values (2, 'Holandesa');
insert into restaurante(nome, taxa_frete, cozinha_id) values('Butcher CWB', 25, 1);
insert into restaurante(nome, taxa_frete, cozinha_id) values('Madalosso', 50, 1);
insert into restaurante(nome, taxa_frete, cozinha_id) values('Dom Antonio', 100, 2);
insert into estado(id,descricao,nome) values (1, 'Paraná', 'PR');
insert into estado(id,descricao,nome) values (2, 'São Paulo', 'SP');
insert into estado(id,descricao,nome) values (3, 'Rio Grande do Sul', 'RS');
insert into cidade(descricao,nome,estado_id) values ('Curitiba', 'Cidade sorriso', 1);
insert into cidade(descricao,nome,estado_id) values ('Campo Magro', 'Cidade verde', 1);
insert into cidade(descricao,nome,estado_id) values ('São Paulo', 'Cidade grande', 2);
insert into forma_pagamento(descricao) values ('Dólar');
insert into forma_pagamento(descricao) values ('Euro');
insert into forma_pagamento(descricao) values ('Real');
insert into permissao_pagamento(nome) values ('Aprovado');
insert into permissao_pagamento(nome) values ('Reprovado');
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id) values (1,1), (1,2),(1,3),(2,1), (2,2), (2,3), (3,2), (3,3);
